kube:
  inCluster: KUBE_USE_CLUSTER
  kubeconfig: KUBE_USE_KUBECONFIG
  current_namespace_only: KUBE_NAMESPACE_ONLY

interval: TICK_RATE
flood_expire: FLOOD_EXPIRE
not_ready_min_time: NOT_READY_MIN_TIME

slack_url: SLACK_URL
